# Generated by Django 3.2.8 on 2022-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('driving', 'Driving'), ('transit', 'Transit')], default='driving', max_length=255),
        ),
    ]
