# Generated by Django 3.2.8 on 2022-04-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options_drive', to='trippin.route'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options_flight', to='trippin.route'),
        ),
        migrations.AlterField(
            model_name='transitroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options_transit', to='trippin.route'),
        ),
    ]
