# Generated by Django 3.2.8 on 2022-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0002_transportation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='airport',
            unique_together=set(),
        ),
    ]
