# Generated by Django 3.2.8 on 2022-04-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0002_remove_routeoption_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportlocation',
            old_name='airport_transportation',
            new_name='transportation',
        ),
    ]
