# Generated by Django 3.2.8 on 2021-11-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aspect', models.CharField(choices=[('SKI', 'Ski'), ('HIKING', 'Hiking'), ('BEACH', 'Beach'), ('MUSEUM', 'Museum'), ('PARTY', 'Party'), ('AMUSEMENT_PARK', 'Amusement_park'), ('CITY', 'City'), ('CULINARY', 'Culinary'), ('LOCAL_CULTURE', 'Local_culture'), ('NIGHT_LIFE', 'Night_life'), ('NONE0', 'None')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
