# Generated by Django 3.2.8 on 2022-02-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0002_alter_interest_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='from_location',
            new_name='location_0',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='to_location',
            new_name='location_1',
        ),
    ]
