# Generated by Django 3.2.8 on 2021-11-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='trippin.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('car', models.FloatField()),
                ('train', models.FloatField()),
                ('bus', models.FloatField()),
                ('walk', models.FloatField()),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippin.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippin.location')),
            ],
            options={
                'unique_together': {('from_location', 'to_location')},
            },
        ),
    ]
