# Generated by Django 3.2.8 on 2022-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0003_auto_20220411_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('driving', 'Driving'), ('transit', 'Transit'), ('flight', 'Flight')], default='driving', max_length=255),
        ),
    ]
