# Generated by Django 3.2.8 on 2022-04-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0003_rename_airport_transportation_airportlocation_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportlocation',
            name='transportation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='trippin.transportation'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airport_location_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_location_0', to='trippin.airportlocation'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airport_location_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_location_1', to='trippin.airportlocation'),
        ),
    ]
