# Generated by Django 3.2.8 on 2022-02-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0003_auto_20220213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='location_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_0', to='trippin.location'),
        ),
        migrations.AlterField(
            model_name='route',
            name='location_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_1', to='trippin.location'),
        ),
    ]
