# Generated by Django 3.2.8 on 2021-11-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0004_auto_20211102_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='lng',
        ),
    ]
