# Generated by Django 3.2.8 on 2022-04-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0004_auto_20220417_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransitRoute',
        ),
    ]
