# Generated by Django 3.2.8 on 2022-04-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0004_alter_transportation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitroute',
            name='route',
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options_flight', to='trippin.route'),
        ),
    ]
