# Generated by Django 3.2.8 on 2022-04-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0005_auto_20220414_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitroute',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_options_transit', to='trippin.route'),
        ),
    ]
