# Generated by Django 3.2.8 on 2022-04-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0005_delete_transitroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='trippin.transportation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
