# Generated by Django 3.2.8 on 2022-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0005_auto_20220220_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driving',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='flight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='transit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='walking',
            field=models.FloatField(null=True),
        ),
    ]
