# Generated by Django 3.2.8 on 2021-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0005_rename_long_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
