# Generated by Django 3.2.8 on 2021-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0006_location_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
