# Generated by Django 3.2.8 on 2022-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0006_transitroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
