# Generated by Django 3.2.8 on 2022-04-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0006_transitroute_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options', to='trippin.route'),
        ),
        migrations.AlterField(
            model_name='transitroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options', to='trippin.route'),
        ),
    ]
