# Generated by Django 3.2.8 on 2022-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0006_auto_20220220_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driving',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='flight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='transit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='walking',
            field=models.IntegerField(null=True),
        ),
    ]
