# Generated by Django 3.2.8 on 2021-11-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0007_location_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('aspect', models.CharField(choices=[('SKI', 'Ski'), ('HIKING', 'Hiking'), ('BEACH', 'Beach'), ('MUSEUM', 'Museum'), ('PARTY', 'Party'), ('AMUSEMENT_PARK', 'Amusement_park'), ('CITY', 'City'), ('CULINARY', 'Culinary'), ('LOCAL_CULTURE', 'Local_culture'), ('NIGHT_LIFE', 'Night_life')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippin.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
