# Generated by Django 3.2.8 on 2022-02-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0007_auto_20220221_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driving',
        ),
        migrations.RemoveField(
            model_name='route',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='route',
            name='transit',
        ),
        migrations.RemoveField(
            model_name='route',
            name='walking',
        ),
        migrations.CreateModel(
            name='TransitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('distance', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('legs', models.IntegerField(null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trippin.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('distance', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('legs', models.IntegerField(null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trippin.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('distance', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('legs', models.IntegerField(null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trippin.route')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
