# Generated by Django 3.2.8 on 2022-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0007_alter_location_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='score',
            field=models.FloatField(default=100),
        ),
    ]
