# Generated by Django 3.2.8 on 2021-11-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0008_auto_20211104_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='route',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='to_location',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
