# Generated by Django 3.2.8 on 2022-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0009_trip_tripsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='aspect',
            field=models.CharField(choices=[('SKI', 'Ski'), ('HIKING', 'Hiking'), ('BEACH', 'Beach'), ('MUSEUM', 'Museum'), ('PARTY', 'Party'), ('AMUSEMENT_PARK', 'Amusement_park'), ('CITY', 'City'), ('CULINARY', 'Culinary'), ('LOCAL_CULTURE', 'Local_culture'), ('NIGHT_LIFE', 'Night_life'), ('PUBLIC_TRANSPORTATION', 'Public_transportation')], max_length=255),
        ),
    ]
