# Generated by Django 3.2.8 on 2022-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0010_alter_airport_iso_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iso_region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
