# Generated by Django 3.2.8 on 2022-05-03 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0011_alter_interest_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='aspect',
            field=models.CharField(choices=[('SKI', 'Ski'), ('HIKING', 'Hiking'), ('BEACH', 'Beach'), ('MUSEUM', 'Museum'), ('PARTY', 'Party'), ('AMUSEMENT_PARK', 'Amusement_park'), ('CITY', 'City'), ('CULINARY', 'Culinary'), ('LOCAL_CULINARY', 'Local_culinary'), ('LOCAL_CULTURE', 'Local_culture'), ('NIGHT_LIFE', 'Night_life'), ('PUBLIC_TRANSPORTATION', 'Public_transportation'), ('HISTORY', 'History'), ('TREKKING', 'Trekking'), ('RAFTING_CANYONING_RAPPELLING', 'Rafting Canyoning Rappelling')], max_length=255),
        ),
        migrations.AlterField(
            model_name='interest',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
    ]
