# Generated by Django 3.2.8 on 2022-03-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0011_alter_airport_iso_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirportRoute',
            new_name='ConnectedAirports',
        ),
    ]
