# Generated by Django 3.2.8 on 2022-03-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0012_rename_airportroute_connectedairports'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectedairports',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='connectedairports',
            name='airport_0',
        ),
        migrations.RemoveField(
            model_name='connectedairports',
            name='airport_1',
        ),
        migrations.RemoveField(
            model_name='drivetype',
            name='route',
        ),
        migrations.RemoveField(
            model_name='flighttype',
            name='route',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='route',
            name='location_0',
        ),
        migrations.RemoveField(
            model_name='route',
            name='location_1',
        ),
        migrations.RemoveField(
            model_name='transittype',
            name='route',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='ConnectedAirports',
        ),
        migrations.DeleteModel(
            name='DriveType',
        ),
        migrations.DeleteModel(
            name='FlightType',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='TransitType',
        ),
    ]
