# Generated by Django 3.2.8 on 2022-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0012_auto_20220503_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
