# Generated by Django 3.2.8 on 2022-03-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0013_auto_20220307_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=255, null=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('continent', models.CharField(max_length=2, null=True)),
                ('iso_region', models.CharField(max_length=255, null=True)),
                ('iso_country', models.CharField(max_length=2, null=True)),
                ('municipality', models.CharField(max_length=255, null=True)),
                ('gps_code', models.CharField(max_length=5, null=True)),
                ('iata_code', models.CharField(max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('location_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_0', to='trippin.location')),
                ('location_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_1', to='trippin.location')),
            ],
            options={
                'unique_together': {('location_0', 'location_1'), ('location_1', 'location_0')},
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('distance', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('legs', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransitRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options', to='trippin.route')),
                ('transportation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='trippin.transportation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='trippin.airport')),
                ('airport_transportation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airport_transportation', to='trippin.transportation')),
                ('flight_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='trippin.transportation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='trippin.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriveRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options', to='trippin.route')),
                ('transportation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='trippin.transportation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('flight_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_0', to='trippin.flight')),
                ('flight_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_1', to='trippin.flight')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_options', to='trippin.route')),
            ],
            options={
                'unique_together': {('flight_1', 'flight_0'), ('flight_0', 'flight_1')},
            },
        ),
        migrations.CreateModel(
            name='AirportConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('airport_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_0', to='trippin.airport')),
                ('airport_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_1', to='trippin.airport')),
            ],
            options={
                'unique_together': {('airport_0', 'airport_1')},
            },
        ),
    ]
