# Generated by Django 3.2.8 on 2022-05-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0013_generallocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralLocation',
            new_name='UserLocation',
        ),
    ]
