# Generated by Django 3.2.8 on 2022-05-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trippin', '0014_rename_generallocation_userlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AlterField(
            model_name='airportlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='trippin.locationcontent'),
        ),
        migrations.AlterField(
            model_name='route',
            name='location_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_0', to='trippin.locationcontent'),
        ),
        migrations.AlterField(
            model_name='route',
            name='location_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_1', to='trippin.locationcontent'),
        ),
    ]
