# Generated by Django 3.2.8 on 2022-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0014_airport_airportconnection_driveroute_flight_flightroute_route_transitroute_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportconnection',
            name='distance',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airportconnection',
            name='travel_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
