# Generated by Django 3.2.8 on 2022-05-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trippin', '0015_auto_20220510_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteOption',
            new_name='RouteContent',
        ),
    ]
