# Generated by Django 3.2.8 on 2022-05-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0016_rename_routeoption_routecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportlocation',
            name='transportation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airport_transportation', to='trippin.transportation'),
        ),
    ]
