# Generated by Django 3.2.8 on 2022-03-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0016_auto_20220309_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='AirportLocation',
        ),
    ]
