# Generated by Django 3.2.8 on 2022-03-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0017_rename_flight_airportlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='airport_location_0',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_location_0', to='trippin.airportlocation'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='airport_location_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_location_1', to='trippin.airportlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='flightroute',
            unique_together={('airport_location_1', 'airport_location_0'), ('airport_location_0', 'airport_location_1')},
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='flight_0',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='flight_1',
        ),
    ]
