# Generated by Django 3.2.8 on 2022-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0018_auto_20220315_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('location_0', 'location_1')},
        ),
    ]
