# Generated by Django 3.2.8 on 2022-03-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0019_alter_route_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airport',
            unique_together={('iata_code', 'id')},
        ),
    ]
