# Generated by Django 3.2.8 on 2022-03-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0020_alter_airport_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airportlocation',
            unique_together={('airport', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='flightroute',
            unique_together={('airport_location_0', 'airport_location_1')},
        ),
    ]
