# Generated by Django 3.2.8 on 2022-03-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0021_auto_20220318_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirportsConnection',
            new_name='AirportsConnection',
        ),
    ]
