# Generated by Django 3.2.8 on 2022-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0022_rename_airportconnection_airportsconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='connections_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
