# Generated by Django 3.2.8 on 2022-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0024_alter_airport_connections_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='metropolitan_iata_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
