# Generated by Django 3.2.8 on 2022-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0025_airport_metropolitan_iata_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='routes_update_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
