# Generated by Django 3.2.8 on 2022-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0030_create_all_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportlocation',
            name='airport_transportation',
        ),
        migrations.RemoveField(
            model_name='driveroute',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='transitroute',
            name='transportation',
        ),
        migrations.AddField(
            model_name='airportlocation',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='airportlocation',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='airportlocation',
            name='legs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driveroute',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driveroute',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driveroute',
            name='legs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transitroute',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transitroute',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transitroute',
            name='legs',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
