# Generated by Django 3.2.8 on 2022-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0031_auto_20220406_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsconnection',
            name='travel_time',
            field=models.FloatField(),
        ),
    ]
