# Generated by Django 3.2.8 on 2022-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trippin', '0031_auto_20220405_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='legs',
            field=models.IntegerField(null=True),
        ),
    ]
