version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
